# Generated by Django 5.0.7 on 2024-09-04 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_tareas_done'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productos',
        ),
    ]
