# Generated by Django 5.0.7 on 2024-09-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_tareas_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='proyecto',
        ),
    ]
