# Generated by Django 5.0.7 on 2024-09-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_remove_tareas_proyecto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proyectos',
        ),
    ]
